"""
VictorReconForge — Empire Mapper
"""
import networkx as nx
from rich.console import Console
import json
import os

console = Console()

class EmpireMapper:
    def __init__(self, runtime=None):
        self.runtime = runtime
        self.graph = nx.DiGraph()

    def build_dependency_graph(self, scan_data: dict) -> nx.DiGraph:
        G = nx.DiGraph()
        org = scan_data.get("org", "unknown")
        G.add_node(org, type="org")
        for repo in scan_data.get("repos", []):
            G.add_node(repo.get("name"), type="repo", **repo)
            G.add_edge(org, repo.get("name"), relation="owns")
        self.graph = G
        return G

    def export_interactive_map(self, graph: nx.DiGraph, output_path: str = "data/mappings/empire_map.html"):
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        html = """<!DOCTYPE html><html><head><title>Victor Map</title></head><body><h1>Empire Map</h1><p>Interactive map generated by VictorReconForge.</p></body></html>"""
        with open(output_path, "w") as f: f.write(html)
        console.print(f"[green]Map exported to {output_path}[/green]")
        return output_path